### ISSUE TITLE
Generate autoload file with only used methods

### ISSUE THREAD

**Issue by KartaviK** [thecodingmachine/safe#130]
Why i must load all functions every request if I, for example, use only few funcs, like `file_get_contents` and `json_encode`

**Comment by andreasschroth** [comment]
Sounds like micro optimisation to me. Don't think it will have any measurable performance impact on your application or what is the purpose of your suggestion?

**Comment by moufmouf** [comment]
If you had to manually import the functions you use, it would make using Safe very impractical.

And indeed, as @andreasschroth puts it, this is a micro optimisation. The whole loading of Safe takes less than 1ms per request.

See https://github.com/thecodingmachine/safe/blob/master/performance/README.md

Unless you have a website with a very very high load, this should really go unnoticed.

Of course, if one day PHP supports function autoloading, I'll be happy to add proper support in Safe. But the RFC looks dead now: https://wiki.php.net/rfc/function_autoloading

**Comment by passcod** [comment]
This adds 15 milliseconds per start to our workloads, which accounts for up to 20% of round trip. That didn't sound like a micro optimisation to us, which is why we went on a hunt to rip out all uses of Safe from our dependencies. We're not really looking for any change here as a result, but just figured you'd appreciate the data point.
