### ISSUE TITLE
Release with PHP8 support

### ISSUE THREAD

**Issue by kunicmarko20** [thecodingmachine/safe#294]
Hi, I am wondering what is missing for you to tag a release that supports php8? Is there anything else that needs to be done?

**Comment by dbrekelmans** [comment]
Hi @kunicmarko20,

I've just released an alpha version which you can try out: https://github.com/thecodingmachine/safe/releases/tag/2.0.0-alpha.1

There are still some bugs to fix before I'm comfortable releasing a stable version.

**Comment by kunicmarko20** [comment]
Thank you @dbrekelmans, we are using it in a big project and so far we didn't run into any issues.

**Comment by DanielRuf** [comment]
@dbrekelmans not sure where I signed up to receive a mass mail regarding the PHP 8 version and Hacktoberfest.

I did not find a "unsubscribe" link so I kindly ask you to remove my email address from your mailing list. Thank you very much.

<img width="625" alt="Bildschirmfoto 2021-10-05 um 10 49 14" src="https://user-images.githubusercontent.com/827205/135991685-49f2e4da-d529-4333-8614-f3a594b9f6f2.png">

**Comment by dbrekelmans** [comment]
Hi @DanielRuf, I'm sorry if this has inconvenienced you. This is not a mailing list, but simply a one-time hand-written invite to collaborate to all previous contributors and people who have shown interest in the PHP8 release of this library through github issues. There will not be any other emails.

**Comment by Jean85** [comment]
@dbrekelmans kudos for pushing this forward! I would suggest to pin this issue (or a similar one with the same invitation as the email) and tag it with the Hacktoberfest label, so people can come here and help!

**Comment by DanielRuf** [comment]
Regarding `hacktoberfest` 2021, you just need to add the `hacktoberfest` topic to the repo to optin to the hacktoberfest event thi year.

I doubt that past contributors with 1 contribution will spend time to provide more PRs.

<img width="309" alt="Bildschirmfoto 2021-10-05 um 11 12 59" src="https://user-images.githubusercontent.com/827205/135995277-773026b1-2f7e-47f4-b4a5-1323d81df595.png">

**Comment by dbrekelmans** [comment]
For anyone who wants to participate tomorrow, the previous discord link seems to have expired.

Here's a new invite link: https://discord.gg/t6UqBQ6k

**Comment by ricardoboss** [comment]
Any updates on this? PHP8.1 is out now aswell. Can I do anything to support this project?

**Comment by dbrekelmans** [comment]
Hi @ricardoboss, sorry for the late response. Both me and @Kharhamel haven't found much time to work on this in a while.

I think I will release a 2.0 version this week. There are still a few bugs, but they all seem very minor and could be fixed in a patch version later.

There are definitely a few things that need to happen to make this library more future proof, like maintaining a delta between PHP versions (as phpstan and psalm do), so docs for 8.1 don't break compatibility for php8.
I will try to create some issues for this as well.

If you are looking to contribute, feel free to look through the issue list and create a PR, it will be very much appreciated!

**Comment by Nadyita** [comment]
Seeing how it's impossible to have missed: why do your replacements for socket functions or `openssl_pkey_new()` return a resource instead of `\Socket` or `\OpenSSLAsymmetricKey`? I don't understand the reasoning behind it, yet I can't believe you overlooked this. Someone enlighten me, please.

**Comment by dbrekelmans** [comment]
Hi @Nadyita, it seems you have found a bug. Your negative phrasing is not very constructive, perhaps it would be helpful for future instances to reconsider how you communicate.

Feel free to create a new issue reporting this bug and/or opening a pull request to fix the bug!

I'm also closing this issue, since 2.0 has been released.
