### ISSUE TITLE
\Safe\array_combine() missing?

### ISSUE THREAD

**Issue by temp** [thecodingmachine/safe#344]
Seems like it completely vanished, shouldn't it at least be deprecated (if the removal was not a mistake)?
It was still available in 2.1.3

See thecodingmachine/phpstan-safe-rule#31, the safe rule is still using \Safe\array_combine, that's where I saw the error.

**Comment by tpetry** [comment]
I am not certain how the deprecation policy is done for the safe library. But I guess it was removed for version 2.2 (which is for PHP 8) because in PHP 8.0 the return type was changed to always return array and throw an exception in case of invalid parameters. The same as this library is doing, which makes it redundant.

PhpStan did detect this missing function for me, so I don't have a problem with the removal.

**Comment by temp** [comment]
Naah, there is a deprecation policy - sprintf moved to deprecated for php 8.0 as well. It showed a warning that sprintf itself is safe since 8.0, so array_combine should be moved there aswell.
The problem with phpstan is not our code, but the phpstan-safe-rule, since this uses the removed function. And thus does not work anymore.

**Comment by Kharhamel** [comment]
Sorry, array_combine was automatically deleted by the generator and I missed that because of another PR with a lot of file rewriting.

The tag 2.2 was deleted anyway because it broked a lot of things. I will publish another tag shortly with a deprecated array_combine function.

**Comment by spawnia** [comment]
Thank you @Kharhamel for dealing with this quickly. Does this library follow semantic versioning? If so, I propose mentioning that in the `README.md`.
