### ISSUE TITLE
php-cs-fixer incompatibility

### ISSUE THREAD

**Issue by staabm** [thecodingmachine/safe#43]
I guess it should be mentioned in the readme that using this lib will create problems with php-cs-fixer. most fixers they ship are tagged with "risky: does not work when you override core method XY in your namespace"

is this a valid problem in combination with this lib?

**Comment by moufmouf** [comment]
Oh, I was not aware of that... 
I'll check this!

**Comment by moufmouf** [comment]
Ok, after checking carefully, I see that the 'native_function_invocation' option is preventing Safe from running because it turns

```
use function Safe\mkdir;
mkdir('foo');
```

into

```
use function Safe\mkdir;
\mkdir('foo');
```

On the other hand this is completely logical and the 'native_function_invocation' is not part of any preset in PHP-CS-Fixer. So if the user enables this preset, I guess he already know what he is doing. I'm a bit reluctant to add something in the README about this incompatibility.

I fear that the "average" reader might misunderstand the problem, and I believe that for developers already using the 'native_function_invocation', the impact will be obvious.

Do you see any other PHP-CS-Fixer risky rule that might cause problems? If not, I'll close the issue.

**Comment by staabm** [comment]
I dont know the full features set of this lib, so I can't say what other things might be influenced.

but yes I intially reported this error because of `native_function_invocation` which is used in some libs for performance reasons (as it fixes the overhead in php to locally lookup native-function names before falling back to native).

maybe it would make sense that the auto-refactor tool would issue a warning when it finds things like `\mkdir` and give the user a hint that this is a problem?

**Comment by soullivaneuh** [comment]
> On the other hand this is completely logical and the 'native_function_invocation' is not part of any preset in PHP-CS-Fixer. So if the user enables this preset, I guess he already know what he is doing. I'm a bit reluctant to add something in the README about this incompatibility.

I must disagree on that. According to the [rule description](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/7455379828759f4266aec11327817bf2ea0e6dc3/doc/rules/function_notation/native_function_invocation.rst):

> Add leading \ before function invocation to speed up resolving.

So it add a `\` prexif to the **native calls**, that's all.

And this is not our case, because we are not using native function, we use yours.

For my case, I installed you library only for few function, so both the cs-fixer rule setting and this lib are useful to me.

A bug report should be opened for php-cs-fixer IMO.

**Comment by dbrekelmans** [comment]
I agree with @soullivaneuh, this is an issue in the rule itself.
