### ISSUE TITLE
Sprintf expects float|int|string|null, Object given

### ISSUE THREAD

**Issue by roukmoute** [thecodingmachine/safe#64]
https://phpstan.org/r/b54e9c9d-6535-492e-b88d-4b566c97edcf

Import this code and replace original `sprintf` with `\Safe\sprintf`.

Now you have anything like:

```sh
 ------ --------------------------------------------------------------------- 
  Line   test.php      
 ------ --------------------------------------------------------------------- 
  7      Parameter #2 $args of function Safe\sprintf expects                  
         float|int|string|null, Baz given.
```

But `Baz` has `__toString()` method and it works with original `sprintf`.

**Comment by Kharhamel** [comment]
Hello, sorry for the year late reply.

Yes this is the problem with using typehints. Sadly there's no way to typehint 'stringeable' objects and one of the big point of this library is to typehint as much as possible, so this issue is probably not going to be solveable. You can still use the default sprintf though.

Sorry about that.

**Comment by andreasschroth** [comment]
The best solution here is probably to cast to a string first before passing the argument - with (string).

E.g. line 7: `return sprintf('%s', (string)$node->operator());`
