### ISSUE TITLE
Argument 2 passed to Safe\openssl_sign() must be of the type string, null given

### ISSUE THREAD

**Issue by JanMikes** [thecodingmachine/safe#86]
Hello!

I have following code:
```php
// $this->privateKey is resource
$digestText = '';
\Safe\openssl_sign($digestText, $signature, $this->privateKey);
```

And i get following error: `Argument 2 passed to Safe\openssl_sign() must be of the type string, null given`

I can get this fixed by adding `$signature = ''` before calling `openssl_sign()`. I understand the error, but i expected (and it worked before using Safe package), that `$signature` variable will get created 😄

**Comment by moufmouf** [comment]
Hey @JanMikes ,

Ok, I can confirm I reproduced the issue in this unit test: #91 .
Still have to find a workaround!

**Comment by moufmouf** [comment]
Ok, found a way.

The PHPStan function map tells us if a parameter passed by reference (like $signature) is supposed to be used for read and write or for write only.

Typically, `$signature` is a write only parameter. Any write only parameter should be considered as nullable (even if they are not documented as such), since we can put null in input and they will produce a string output.

**PHPStan's functionMap.php**
```
'openssl_sign' => ['bool', 'data'=>'string', '&w_signature'=>'string', 'priv_key_id'=>'resource|string', 'signature_alg='=>'int|string'],
``` 

The "w_" in the file denotes the "write only" mode.

**Comment by JanMikes** [comment]
Thank you very much, I will try it out.
