### ISSUE TITLE
Add phpcs rule?

### ISSUE THREAD

**Issue by roukmoute** [thecodingmachine/safe#89]
Hi,

What do you think about to add new repository to fix automatically via phpcs or phpcsfixer all imports instead of just detecting it via phpstan?

**Comment by moufmouf** [comment]
Hey @roukmoute ,

I'm not a PHPCS or PHP-CS-Fixer expert but I'm not sure these tools can work in the case of Safe (because they must understand if a given function is part of the Safe namespace or not).

So far, you can use "Rector" to automatically fix these imports: https://github.com/thecodingmachine/safe#automated-refactoring
It's a bit like PHP-CS-Fixer but it acts at the abstract syntax tree level.

Note: If you know how to write such a rule for PHPCS or PHP-CS-Fixer, I'd be delighted to create a separate repository for such a feature.
