### ISSUE TITLE
Removing functionality is never a minor change! (array_search and mb_check_encoding)

### ISSUE THREAD

**Issue by vdvleon** [thecodingmachine/safe#92]
In version v0.1.12 array_search and mb_check_encoding were removed from supported functions.
However, this is a major change! Some projects break on this because they have dependencies like "^0.1.11". I think the functions should be returned in version v0.1.13, and then re-removed as a major update v1.0.0.

**Comment by bolmstedt** [comment]
Well, https://semver.org/#spec-item-4 states that:
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So it's technically not wrong. If anything, it might be nice to at least only make BC incompatible changes in a minor (y) version.

**Comment by kibertoad** [comment]
@bolmstedt Technically - yes, you are right. However, when an open-source library becomes actively used, `initial development` phase is in practice over; it's a much more community-friendly approach to avoid breaking changes or at least communicate these changes in advance to popular projects that depend on the library.

**Comment by moufmouf** [comment]
Hey guys!

> However, when an open-source library becomes actively used, initial development phase is in practice over;

You are absolutely right. The problem is that it is hard to know when a library can be considered as actively used.

I made the BC break willingly, thinking nobody was actively using `Safe\array_search` or `Safe\mb_check_encoding`.
It seems I was wrong, Safe is more used than I used to think (\o/)
The fact that @vdvleon is opening this issue is a good marker that it is actively used, but I had to make the BC break to be notified :)

So, as of today, I'll refrain from making any breaking changes in 0.1.x versions and I'll update the minor for each BC breaks.

... and thanks for using Safe and for the feedback!
