### ISSUE TITLE
Safe\preg_replace fails PHPStan check

### ISSUE THREAD

**Issue by acabal** [thecodingmachine/safe#94]
Given the following minimal test case:

```php
<?php
require __DIR__ . 'vendor/autoload.php';

use function Safe\preg_replace;

$x = preg_replace('/foo/', 'bar', 'baz');
$y = stripos($x, 'foo');
?>
```

When running `phpstan analyse -l 7` on the above, it outputs: `Parameter #1 $haystack of function stripos expects string, array|string given.`

This is because `preg_replace()` can return either a string or an array depending on what the third parameter is. In this case, the third parameter is a string, so it should return a string and we should be OK. In fact without Safe, PHPStan does not report an error. But when using Safe, PHPStan seems to get confused about the third parameter and reports a type error even though the code is in fact correct.

I'm not sure if this is a Safe issue or a PHPStan issue but because the two projects are closely related in function I thought I'd report it here first to see.

**Comment by jderusse** [comment]
As you said, the return type of the method depend on the type of the parameter, that's why the PHPDoc is not enougth in a static analysis context: the analyser have to know how the method works, OR have to read and understand the documentation, which is not the case of PHPStan.

PHPStan is able to analyse the `\preg_replace` function because a special extension has been implemented to cover that case (see https://github.com/phpstan/phpstan/blob/master/src/Type/Php/ReplaceFunctionsDynamicReturnTypeExtension.php) which is not the case of `\Safe\preg_replace`.

This "issue" is not related to `Safe` and should be fix in PHPStan or the ReplaceFunctionsDynamicReturnTypeExtension could be backported  in https://github.com/thecodingmachine/phpstan-safe-rule in order to include \Safe\preg_replace method

**Comment by acabal** [comment]
OK, I'll report this to PHPStan to see what they say. Thanks!

**Comment by acabal** [comment]
FYI PHPStan [kicked the issue back here](https://github.com/phpstan/phpstan/issues/1932) and say to implement it in https://github.com/thecodingmachine/phpstan-safe-rule

In either case it doesn't make sense for us to use Safe, when doing so causes PHPStan to output errors for correct code. :(

**Comment by moufmouf** [comment]
PHPStan was right to kick the issue back here. Thanks @jderusse for pointing the "ReplaceFunctionsDynamicReturnTypeExtension.php". I backported it to Safe\preg_replace in https://github.com/thecodingmachine/phpstan-safe-rule/pull/10

**Comment by acabal** [comment]
Awesome, thanks! :)
